version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: bookmarks-redis

    postgres:
      image: postgres:alpine
      container_name: bookmarks-postgres
      volumes:
         - "./db/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
       - "5432:5432"
      networks:
            testing_net:
                ipv4_address: 172.28.1.2
    webserver:
      image: nginx:alpine
    #   build: docker/nginx
      container_name: bookmarks-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./docker/nginx:/etc/nginx/conf.d
      ports:
       - "8081:80"
      networks:
            testing_net:
                ipv4_address: 172.28.1.3

    php-fpm:
      build: docker/php-fpm
      container_name: bookmarks-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
          testing_net:
              ipv4_address: 172.28.1.4
    frontend:
      build: docker/frontend
      container_name: bookmarks-frontend
      working_dir: /application
      volumes:
        - ./application:/application
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16